### ISSUE TITLE
Open the Chromium DevTools (Console/Inspect element) via the F12 shortcut

### ISSUE THREAD

**Issue by PostMalone** [WesselKroos/race-tv-multiplayer#6]
For reasons i can only login using F1TV cookies (login session) and not the standard way of logging in (email:password).

I'm wondering if its possible to somehow open a Console (Inspect element - F12) and then edit the cookie? It appears that the F12 button and right clicking is not allowed on RaceTV Multiplayer. This works for example on RaceControl. 

Let me know, thanks.

**Comment by WesselKroos** [comment]
@PostMalone Electron apps work slightly different from a normal browser. You can open the Chromium DevTools via the shortcut `Left ctrl + Left shift + i` instead. 

I'll probably add a F12 shortcut in the future.

**Comment by PostMalone** [comment]
Thank you so much @WesselKroos , i had no idea this was Electron. Sorry about that.

Left ctrl + Left Shift + i does the job. 

Cheers!
